const User = {
  recnum: "",
  fstnme: "",
  lstnme: "",
  e_mail: "",
  cllphn: "",
  usrnme: "",
  passwd: "",
};

export const ExpInfoValues = {
  modelStreetAddr: "",
  modelCity: "",
  modelState: "",
  modelZip: "",
  designStreetAddr: "",
  designCity: "",
  designState: "",
  designsZip: "",
  expMisc: "",
  vendorPortal: "",
  wasteFactor: "",
  patternCharges: "",
};

export const AcctInfoValues = {
  taxID: "",
  paymentDay: "",
  paymentFreq: "",
  howToSubmitInv: "",
  whoReceivesInv: "",
  invSubmitDeadline: "",
  paymentType: "",
  paymentPortal: "",
  vendorID: "",
  acctMisc: "",
  autopayToggle: false,
  checkPUToggle: false,
  portalToggle: false,
  vendorIDToggle: false,
  POToggle: false,
  poCorrection: "",
  approvalsToggle: false,
};

const Contact1 = {
  contct: "",
  cntds1: "",
  phnnum: "",
  phnext: "",
  faxnum: "",
  cllphn: "",
  pagnum: "",
  e_mail: ""
};

const Contact2 = {
  contc2: "",
  cntds2: "",
  phn002: "",
  phext2: "",
  fax002: "",
  cell02: "",
  pagr02: "",
  email2: ""
};

const Contact3 = {
  contc3: "",
  cntds3: "",
  phn003: "",
  phext3: "",
  fax003: "",
  cell03: "",
  pagr03: "",
  email3: ""
};

const Client = {
  shtnme: "",
  clnnme: "",
  grting: null,
  addrs1: "",
  addrs2: "",
  ctynme: "",
  state_: "",
  zipcde: "",
  bilad1: "",
  bilad2: "",
  bilcty: "",
  bilste: "",
  bilzip: "",
  shpad1: "",
  shpad2: "",
  shpcty: "",
  shpste: "",
  shpzip: "",
  usrdf1: null,
  usrdf2: null,
  usrdf3: null,
  usrdf4: null,
  usrdf5: null,
  usrdf6: null,
  usrdf7: null,
  usrdf8: null,
  usrdf9: null,
  contct: null,
  contc2: null,
  contc3: null,
  cntds1: null,
  cntds2: null,
  cntds3: null,
  phnnum: null,
  phn002: null,
  phn003: null,
  phnext: null,
  phext2: null,
  phext3: null,
  faxnum: null,
  fax002: null,
  fax003: null,
  cllphn: null,
  cell02: null,
  cell03: null,
  pagnum: null,
  pagr02: null,
  pagr03: null,
  e_mail: null,
  email2: null,
  email3: null,
  dtercv: null,
  empnum: null,
  mannum: 1010,
  taxdst: null,
  lstctc: null,
  cllbck: null,
  lstmal: null,
  lstdte: null,
  pchdte: null,
  refdte: null,
  prdnum: null,
  dscrte: null,
  duetrm: null,
  finrte: null,
  ledsrc: null,
  clntyp: 1,
  status: 1,
  mallst: null,
  region: null,
  cmpsze: null,
  srvcon: null,
  srvexp: null,
  clndsc: null,
  begbal: null,
  endbal: null,
  maploc: null,
  crsstr: null,
  bilbas: null,
  pchnum: null,
  exmnum: null,
  crdnum: null,
  expdte: null,
  crdnme: null,
  crdtyp: null,
  ntetxt: null,
  catxex: null,
  pstexm: null,
  inactv: null,
  stmeml: null,
};

export { 
  User, 
  Client,
  Contact1,
  Contact2,
  Contact3
};
